/**
 * @sns-agent/sdk - TypeScript SDK
 *
 * CLI と Web UI が共通利用する API クライアント SDK。
 * fetch ベースの HTTP クライアント、リソース別メソッド、型定義、エラー型を提供する。
 */

// Client
export { SnsAgentClient } from "./client.js";
export type {
  SnsAgentClientOptions,
  SnsAgentHttpMethod,
  SnsAgentRequestOptions,
  AccountsResource,
  PostsResource,
  SchedulesResource,
  UsageResource,
  BudgetResource,
  EngagementGatesResource,
  FollowersResource,
  TagsResource,
  FollowerAnalyticsResource,
  CampaignsResource,
  QuoteTweetsResource,
  StepSequencesResource,
  AgentResource,
} from "./client.js";

// Types
export type {
  ApiResponse,
  ApiErrorResponse,
  PaginationMeta,
  ConnectAccountInput,
  ListPostsParams,
  CreatePostInput,
  UpdatePostInput,
  ListSchedulesParams,
  CreateScheduleInput,
  UpdateScheduleInput,
  RunDueSchedulesInput,
  RunDueSchedulesJobResult,
  RunDueSchedulesResult,
  UsageReportParams,
  UsagePeriod,
  UsageReportEntry,
  UsageReportMeta,
  UsageSummary,
  UsageSummaryReport,
  OffsetPaginationMeta,
  OffsetApiResponse,
  XDateStampedDto,
  FollowerDto,
  ListFollowersParams,
  SyncFollowersInput,
  SyncFollowersResultDto,
  FollowerTagInput,
  TagDto,
  ListTagsParams,
  CreateTagDto,
  UpdateTagDto,
  FollowerAnalyticsParams,
  FollowerAnalyticsPointDto,
  FollowerAnalyticsResultDto,
  CaptureFollowerSnapshotDto,
  FollowerSnapshotDto,
  CaptureFollowerSnapshotResultDto,
  CaptureFollowerSnapshotsForWorkspaceResultDto,
  BudgetScopeType,
  BudgetPeriodType,
  BudgetActionOnExceed,
  BudgetPolicyDto,
  BudgetStatusDto,
  CreateBudgetPolicyDto,
  UpdateBudgetPolicyDto,
  EngagementGateConditionsDto,
  EngagementGateStatusDto,
  EngagementGateActionTypeDto,
  EngagementGateStealthConfigDto,
  EngagementGateDto,
  ListEngagementGatesParams,
  CreateEngagementGateDto,
  UpdateEngagementGateDto,
  VerifyEngagementGateParams,
  VerifyEngagementGateResultDto,
  ConsumeEngagementGateDeliveryTokenDto,
  ConsumeEngagementGateDeliveryTokenResultDto,
  ProcessEngagementGateRepliesDto,
  ProcessEngagementGateRepliesResultDto,
  CampaignModeDto,
  CampaignPostInputDto,
  CreateCampaignDto,
  CampaignRecordDto,
  CampaignListItemDto,
  QuoteTweetActionTypeDto,
  QuoteTweetDto,
  ListQuoteTweetsParams,
  SyncQuoteTweetsDto,
  SyncQuoteTweetsResultDto,
  QuoteTweetActionDto,
  QuoteTweetActionResultDto,
  ListStepSequencesParams,
  StepSequenceStepDto,
  CreateStepSequenceDto,
  StepSequenceDto,
  EnrollStepSequenceDto,
  StepSequenceEnrollmentDto,
  SocialAccount,
  Post,
  PostProviderMetadata,
  ScheduledJob,
  UsageRecord,
  MediaAttachment,
  Platform,
  AgentExecutionMode,
  AgentSkillIntent,
  AgentSkillPreview,
  AgentChatTextResponse,
  AgentChatPreviewResponse,
  AgentChatResponse,
  AgentChatInput,
  AgentExecuteInput,
  AgentExecuteResponse,
  AgentHistoryEntry,
  AgentHistoryParams,
} from "./types.js";

// Errors
export { SdkError } from "./errors.js";
